ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "learn_nbdev_today"
  site-url: "https://dirkkalmbach.github.io/learn_nbdev_today/"
  description: "A description of your project"
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/dirkkalmbach/learn_nbdev_today/tree/master/"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/dirkkalmbach/learn_nbdev_today/tree/master/"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
