# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/learn_nbdev_today/',
                'doc_host': 'https://dirkkalmbach.github.io',
                'git_url': 'https://github.com/dirkkalmbach/learn_nbdev_today/tree/master/',
                'lib_path': 'learn_nbdev_today'},
  'syms': {'learn_nbdev_today.core': {}}}