# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://dirkkalmbach.github.io/learn_nbdev_today/"

git_url = "https://github.com/dirkkalmbach/learn_nbdev_today/tree/master/"

def custom_doc_links(name): return None
