# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
from IPython.display import display,SVG

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'